Add g:linuxsty_save_path configuration
gregkh/kernel-coding-style pull request #2
Opened 2023-08-17 14:35 UTC by qianqiangliu

When the configuration is set to 1, linuxsty will remember the current file's directory and will automatically invoke LinuxCodingStyle next time.

2023-08-19 20:29 UTC, gregkh commented
Thanks for this, it looks nice.  But can you also document it properly so that people know how to use it and that it is a feature?

2023-08-19 20:29 UTC, gregkh requested changes
Needs to be documented somewhere so that people know to use it.

2023-08-19 22:45 UTC, qianqiangliu commented
> Needs to be documented somewhere so that people know to use it.

Please review again.

2023-08-20 08:57 UTC, gregkh approved these changes

2023-08-20 08:57 UTC, gregkh approved these changes

2023-08-20 08:58 UTC, gregkh commented
Looks great, thanks!

2023-08-20 08:58 UTC, merged